[build]
  publish = "dist/auction.io/browser"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  NPM_FLAGS = "--include=dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 4200
  publish = "dist/auction.io/browser" 